module.exports = {
    apps: [{
        name: 'Project_Management',
        script: 'index.js',
        instances: 1,
        autorestart: true,
        watch: true,
        max_memory_restart: '1G',
        env: {
            NODE_ENV: 'development',
            PASSWORD_ADMIN: '12345678',
            LOGGER_CONSOLE_ENABLE: true,
            LOGGER_CONSOLE_LEVEL: 'debug',
            LOGGER_FILE_ENABLE: false,
            LOGGER_FILE_LEVEL: 'warn',
            LOGGER_FILE_PATH: './logs',
            LOGGER_FILE_NAME: 'project-management-api.log',
            LOGGER_FILE_MAX_SIZE: '1048576',
            MIM_DB_HOST: '127.0.0.1',
            MIM_DB_PORT: 3306,
            MIM_DB_USERNAME: 'root',
            MIM_DB_PASSWORD: '123456',
            MIM_DB_DATABASE: 'project-management',
            MIM_DB_TIMEZONE: 'Etc/GMT0',
            MIM_DB_LOGGER_ENABLE: true,
            SERVER_PORT: 3000,
            SERVER_FILE_LOCATION: './uploads',
            EMAIL_NO_REPLY_ADDRESS: 'noreply@digitechglobalco.com',
            EMAIL_NO_REPLY_PASSWORD: 'EvJDm38bkuvTPSmm',
            FRONTEND_PAGE_URL: 'http://localhost:3001',
            RECAPTCHA_SKIP: true,
            RECAPTCHA_V2_SITE_KEY: '6LfeCLUUAAAAALLSgBWnBu4zb49-igc4oIUCNAI7',
            RECAPTCHA_V2_SECRET_KEY: '6LfeCLUUAAAAAHUzaPowhvsLCyWaArifjEAvQQFp',
        },
    }],
};
